language: python
python:
  - '3.5'
  - 3.5-dev
  - '3.6'
  - 3.6-dev

matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - nosetests -v --with-coverage --cover-package=ncbi_cds_from_protein

dist: trusty
sudo: false
after_success:
  - codecov

deploy:
  provider: pypi
  user: widdowquinn
  password:
    secure: GXX6ogxXYZRyXLbSN6nT1iETVE+aSBdl2b0+YXE6NfzRRH4WA540hwaU8fpJq7svFIwZXR+xl3gCZxi4jO72nm6xJOF9ogjMd5D/tLIHKR9mu7BN5kUPNJs5Faby0x2yuppT4WoU5g0o+0tExNS0soNSbxTp283WvIehngtrJoJFYzCSW8jH0lPFnGpHpZ+iEYRP3hAd3NGMhMqxklS3hNQNqAA7hEEtq9PQ6c11LVda4adHlY+jKBRrjl057Kq5NC9f+N1BQLuIpfy9ScRDQOqQpiDSgplIQStef8w7ErMFCOEJTEnKUackMAFH1v7aK5u4cUHsnmYQqi8JqisPjBpV/z6YlTEsDdCwhCdzs6i2PNf84xQzz988rGywTsg5tLLn2acddlaUrdQUzAOYQfqKZLlzrhOe81bTfjTba28ZwIkpBDkhU2BUNd2VBL3EGKv2F2b+3LoeVzTfN3vMc5jfnP/1BJZFNwhvuNOlD2vjlmcm9mDU0ovznbGyUujB6sCJ7Kl07Bo4TiMCjo0L0PjcvIUoNeJk8+7gnJtRQpWoNYh8/ikNA0GhU1ShRyNcWg7agtRXkJRfjSFATKpuJZkabXRUDdf43zjPmfI8iFTX691+A2CwAGpIqe+Dj5W0nn+0EZu6sAIZG8FuEGKQG2Hi1iKlw5pEepz4yyksKHc=
  distributions: sdist bdist_wheel
  on:
    tags: true

