language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev

matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

install:
- pip install -r requirements.txt
- pip install codecov

script:
- nosetests -v --with-coverage --cover-package=ncbi_cds_from_protein

dist: trusty
sudo: false

after_success:
- codecov
